import { chromium,firefox,webkit } from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import { mkdir,writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { createServer } from './serve.mjs';
const live=process.argv.includes('--live');
const selected=process.argv.find(arg=>['--chromium','--firefox','--webkit'].includes(arg))?.slice(2);
const outputPrefix=(live?'live-':'')+(selected?selected+'-':process.argv.includes('--edge')?'edge-':'');
const server=live?null:createServer();if(server)await new Promise(resolve=>server.listen(4173,'127.0.0.1',resolve));
await mkdir('qa-artifacts',{recursive:true});
const base=live?'https://lastar.me':'http://127.0.0.1:4173';const routes=['/','/download','/privacy','/terms','/community-guidelines','/safety','/delete-account','/changelog','/not-a-page'];
const results=[];let failed=false;
try{for(const [name,engine]of Object.entries(process.argv.includes('--edge')?{edge:chromium}:selected?{[selected]:{chromium,firefox,webkit}[selected]}:{chromium,firefox,webkit})){const browser=await engine.launch(name==='edge'?{channel:'msedge'}:{});try{for(const [width,height]of [[320,568],[360,800],[390,844],[430,932],[768,1024],[1440,1000]]){const context=await browser.newContext({viewport:{width,height},reducedMotion:'reduce'});const page=await context.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));for(const route of routes){const response=await page.goto(base+route);await page.locator('img').evaluateAll(images=>Promise.all(images.map(img=>{img.loading='eager';return img.decode();})));assert.equal(response.status(),route==='/not-a-page'?404:200);assert.ok(await page.locator('h1').isVisible());const overflow=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth}));assert.ok(overflow.scroll<=overflow.client+1,`${name} ${width} ${route}: horizontal overflow ${JSON.stringify(overflow)}`);const broken=await page.locator('img').evaluateAll(images=>images.filter(img=>img.complete&&img.naturalWidth===0).map(img=>img.src));assert.deepEqual(broken,[]);if(['chromium','edge'].includes(name)&&(width===390||width===1440)){await page.screenshot({path:`qa-artifacts/${live?'live-':''}${width===390?'mobile':'desktop'}-${route==='/'?'home':route.slice(1)}.png`,fullPage:true});const accessibility=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.deepEqual(accessibility.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)})),[],`${route} accessibility`);}results.push(`${name} ${width}x${height} ${route} PASS`);}assert.deepEqual(errors,[]);await context.close();}
// Agent-specific behavior remains deterministic and does not redirect automatically.
for(const [kind,ua]of Object.entries({wechat:'Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 Chrome/120 Mobile Safari/537.36 MicroMessenger/8.0.49',android:'Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 Chrome/120 Mobile Safari/537.36',ios:'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 Version/17.0 Mobile/15E148 Safari/604.1'})){const context=await browser.newContext({viewport:{width:390,height:844},userAgent:ua,reducedMotion:'reduce'});const page=await context.newPage();await page.goto(base+'/download');assert.equal(await page.locator('[data-wechat]').isVisible(),kind==='wechat');assert.equal(await page.locator('[data-ios]').isVisible(),kind==='ios');assert.equal(await page.locator('[data-desktop]').isVisible(),false);if(kind==='ios')for(const button of await page.locator('[data-apk]').all())assert.equal(await button.isVisible(),false);if(['chromium','edge'].includes(name)&&kind==='wechat')await page.screenshot({path:`qa-artifacts/${live?'live-':''}wechat-mode.png`,fullPage:true});await context.close();results.push(`${name} ${kind} UA PASS`);}
const context=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});const page=await context.newPage();await page.goto(base);assert.equal(await page.locator('.planet').evaluate(el=>getComputedStyle(el).animationName),'none');assert.equal(await page.locator('.meteor').evaluate(el=>getComputedStyle(el).animationName),'none');if(name==='webkit'){/* WebKit link traversal follows OS keyboard preferences; verify focused-anchor keyboard activation explicitly. */await page.locator('.skip').focus();}else{await page.keyboard.press('Tab');}assert.equal(await page.locator('.skip').evaluate(el=>el===document.activeElement),true);await page.keyboard.press('Enter');await page.waitForURL('**/#main');await page.locator('details summary').first().click();assert.ok(await page.locator('details').first().getAttribute('open')!==null);await page.evaluate(()=>document.documentElement.style.fontSize='200%');const resize=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth,offenders:[...document.querySelectorAll('body *')].filter(el=>el.getBoundingClientRect().right>innerWidth+1).map(el=>({tag:el.tagName,class:el.className,text:el.textContent.slice(0,80),right:el.getBoundingClientRect().right,parentOverflow:el.parentElement?getComputedStyle(el.parentElement).overflow:null}))}));await page.screenshot({path:`qa-artifacts/${outputPrefix}${name}-text-200.png`,fullPage:true});assert.ok(resize.scroll<=resize.client+1,`200% text resize overflow: ${JSON.stringify(resize)}`);await context.close();results.push(`${name} keyboard activation, FAQ, reduced motion, 200% text resize PASS`);
}finally{await browser.close();}}}catch(error){failed=true;results.push(`FAIL: ${error.stack}`);}finally{server?.close();await writeFile(`qa-artifacts/${outputPrefix}results.txt`,results.join('\n'));console.log(results.join('\n'));if(failed)process.exitCode=1;}
